### PR TITLE
Routing Integration

### LINKED ISSUE #8: Remove getToAddress() from physical device code
as of #7 , getToAddress() is no longer required, but is still inside the physical device code

### PR DESCRIPTION
**Pull request by s-axford**
Adds routing to physical device directory. 

Compiles onto devices, but is untested with mobile application. Once app can talk with routing this can be merged

### CODE REVIEW

**Comment by s-axford** [comment]
Related to https://github.com/chirpnets/chirp-nets-mobile/pull/12

**Comment by s-axford** [comment]
Tested confirmed working with mobile application as of https://github.com/chirpnets/chirp-nets-mobile/pull/12

**Review by JeremyButt — APPROVED** [review]
Looks good! :)

**Comment by JeremyButt** [comment]
Merging and overriding 2 approvals as @johnnyb8 was there while developing solution

**Pull request merged**
